[theme]
primaryColor = "#E94560"
backgroundColor = "#1A1A2E"
secondaryBackgroundColor = "#16213E"
textColor = "#EDF2F4"
font = "sans serif"

[server]
maxUploadSize = 50
enableCORS = false

[browser]
gatherUsageStats = false
